config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  # route for new method
  get 'todos/new'
  # route for created method
  post 'todos', to: 'todos#create'
  # route for list method
  get 'todos/list'
  # route for show method
  get 'todos/:id', to: 'todos#show', as: 'todo'
  # route for edit method
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
  # route for update method
  patch 'todos/:id', to: 'todos#update'
  # route for destroy method
  delete 'todos/:id', to: 'todos#destroy'
  
  # route for complete method
  get 'todos/:id', to: 'todos#complete'
  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

    def index
        @todos = Todo.all
    end

    def new
        @todo = Todo.new
    end

    def create
        @todo = Todo.new(todo_params)
        @todo.save
        redirect_to todos_path
    end

    def show
        @todo = Todo.find(params[:id])
        if @todo.completed
            @status = 'Complete'
        else
            @status = 'Not completed'
        end
    end

    def edit
        @todo = Todo.find(params[:id])
    end

    def update
        @todo = Todo.find(params[:id])
        @todo.update(todo_params)
        redirect_to todos_path
    end
    
    def destroy
        @todo = Todo.find(params[:id])
        @todo.destroy
        redirect_to todos_path
    end

    def complete
        @todo = Todo.find(params[:id])
        @todo.completed = true
        @todo.save
        redirect_to todos_path
    end
    
    def list
        @todos = Todo.all
    end
    
    private
    def todo_params
        params.require(:todo).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B"
      crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |t| %>
  <div class="card myform">
    <%= t.label :description, "ToDo" %>
    <%= t.text_field :description %>

    <%= t.label :completed, "Done" %>
    <%= t.check_box :completed %>

    <%= t.submit "Save", class: 'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="navbar-header">
    <a class="navbar-brand" <%=link_to "ToDos", todos_path %></a>
  </div>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to "Index", todos_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "List", todos_list_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to "Create", todos_new_path, class: 'nav-link' %></li>
    </ul>
  </div>
</nav>

app/views/todos/edit.html.erb
<div class="container-fluid blur">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-5">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/todos/form_partial.html.erb
<%= form_with model: @todo, local: true do |t| %>
  <div class="well">
    <%= t.label :description, "ToDo" %>
    <%= t.text_field :description %>

    <%= t.label :completed, "Done" %>
    <%= t.check_box :completed %>

    <%= t.submit "Save" %>
  </div>
<% end %>

app/views/todos/index.html.erb
<div class="p-5">
  <h4><%= link_to 'Create ToDo Task', todos_new_path, class: 'btn btn-danger' %></h4>
</div>
<% @todos.each do |t| %>
  <div class="card card-ToDo bg-faded p-5">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h5><%= t.description %></h5>
        </div>
        <div class="col-md-6 text-center">
          <ul>
            <li class="crd-btn">
              <%= link_to 'Show', todo_path(t.id), class:'btn btn-success' %>
            </li>
            <li class="crd-btn">
              <%= link_to 'Edit', edit_todo_path(t.id), class:'btn btn-info' %>
            </li>
            <li class="crd-btn">
              <%= link_to 'Delete', t, method: :delete, class: 'btn btn-danger' %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/todos/list.html.erb
<div class="container-fluid">
    <div class="row m-4">
        <div class="col-md-6">
            <h1 class="text-center">ToDo Still not Finished</h1>
            <br>
            <table class="table">
                <thead class="thead-dark">
                    <th> ID </th>
                    <th> Description Task </th>
                </thead>
            <% @todos.each do |t| %>
                <% if t.completed == false %>
                    <tbody>
                        <td> <%= "#{t.id}" %> </td>
                        <td> <%= t.description %></td>
                    </tbody>
                
                <% end %>
            <% end %>
            </table>
        </div>
        <div class="col-md-6">
            <h1 class="text-center">ToDo Finished</h1>
            <br>
            <table class="table">
                <thead class="thead-dark">
                    <th> ID </th>
                    <th> Description Task </th>
                </thead>
                <% @todos.each do |t| %>
                    <% if t.completed %>
                        <tbody>
                            <td>
                                <%= "#{t.id}" %>
                            </td>
                            <td>
                                <%= t.description %>
                            </td>
                        </tbody>
                    <% end %>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/todos/new.html.erb
<div class="container-fluid blur">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-5">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/todos/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 mt-5">
            <h3><%= "ToDo Nº #{@todo.id}" %></h3>
            <div class="container">
                <h5><%= "Description: #{@todo.description}" %></h5>
                <h5><%= "State: #{@status}" %></h5>
            </div>
        </div>
    </div>
</div>